In [1]:
# Importing NumPy Array
import numpy as np

In [2]:
numpyArray = np.array([[2, 4, 6],[6, 8, 10]])
print(numpyArray)

[[ 2  4  6]
 [ 6  8 10]]


In [3]:
numpyArray.dtype = "float64"
print(numpyArray.dtype)

float64


In [4]:
print(numpyArray)

[[1.e-323 2.e-323 3.e-323]
 [3.e-323 4.e-323 5.e-323]]
