In [1]:
# Importing NumPy Package
import numpy as np

In [2]:
onesArray = np.ones((3,3))

In [3]:
zerosArray = np.zeros((5,5))

In [4]:
zerosArray[1:4,1:4] = onesArray
print(zerosArray)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]
