In [1]:
# Importing NumPy Package
import numpy as np

In [3]:
# Generating a 3*3 Random Matrix ranging between 2 and 10
random_matrix = np.random.randint(2,11,(3,3))
print(random_matrix)

[[ 2  8 10]
 [ 9  7  9]
 [ 5  6  2]]
