In [1]:
# Importing NumPy Package
import numpy as np

In [2]:
# Creating the Array Containing 1's and 0's 
onesArray = np.ones((5,5))
zerosArray = np.zeros((3,3))

In [3]:
# Putting the Zeros on appropriate position
onesArray[1:4, 1:4] = zerosArray
print(onesArray)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
